### ISSUE TITLE
No valid Rocksmith file sets found in working directory or Steam user directories

### ISSUE THREAD

**Issue by daijoubu** [BuongiornoTexas/rsrtools#15]
I'm unable to get importrsm to work.  When I follow the instructions to clone a profile, I get errors.  I tried dumping my profile and get the following error.  I believe it's because my Steam user directories are 9 digits long and the code is looking for 8 digit directory names.
(Env) D:\RS_Stuff\Working>profilemanager --dump-profile "D:\RS_Stuff\Working"
WARNING:root:Steam metadata file remotecache.vdf expected but not found in:
   D:\RS_Stuff\Working\RS_working
WARNING:root:Rocksmith local profiles file expected but not found:
   File D:\RS_Stuff\Working\RS_working\remote\LocalProfiles.json is missing.
WARNING:root:Warning: No Rocksmith save files (_PRFLDB) found in:
    D:\RS_Stuff\Working\RS_working\remote.
Traceback (most recent call last):
  File "C:\Users\daijo\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\daijo\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\RS_Stuff\Env\Scripts\profilemanager.exe\__main__.py", line 7, in <module>
  File "d:\rs_stuff\env\lib\site-packages\rsrtools\files\profilemanager.py", line 2237, in main
    pm = RSProfileManager(working)
  File "d:\rs_stuff\env\lib\site-packages\rsrtools\files\profilemanager.py", line 1215, in __init__
    self._steam_account_id, chosen_file_set = self._choose_file_set(
  File "d:\rs_stuff\env\lib\site-packages\rsrtools\files\profilemanager.py", line 1349, in _choose_file_set
    raise RSFileSetError(
rsrtools.files.profilemanager.RSFileSetError: No valid Rocksmith file sets found in working directory or Steam user directories (fatal error).

**Comment by daijoubu** [comment]
Changing line 326 of Steam.py to look for nine digit folders now gets me a prompt of which Steam account to use instead of crashing.
if len(child.name) == 9 and child.name.isdigit():

**Comment by BuongiornoTexas** [comment]
Hi @daijoubu, 

My apologies - I missed the notification of this issue and only saw the report today. I'm happy to update the code, but I need a bit more detail on 9 digit steam ids (either some pseudo code or a link to an explanation of how they work). Specifically, I need a systematic way to identify when a steam user has a 9 digit id (e.g. is a regional thing) and a way to calculate it from date available in the steam folder.

**Comment by daijoubu** [comment]
No problem, I fixed my instance.  From my research, Steam Ids are actually 31 bit integers with the leading zeros dropped.  So Steam Ids are anything up to 2,147,483,647.  I don't know enough about the Steam API to query for the ID of the current user though.

**Comment by BuongiornoTexas** [comment]
Ah - I'm guessing I assumed that all SteamIDs were 8 digit based on the limited sample I had available. I think the fix should be as simple as removing the length check on the folder name. I'll do the fix shortly, as I need to sort another issue for multi-drive libraries.
