### ISSUE TITLE
WARNING:root:Rocksmith save file has no player name:

### ISSUE THREAD

**Issue by kevinl7778** [BuongiornoTexas/rsrtools#18]
Hello, I have python 3.11.5 and i get this error when cloning the game profile "WARNING:root:Rocksmith save file has no player name:" and this causes the prifile files to not populate the RS_working folder.

My goal is to use the rocksmith manager to easaly chang up setlist.playlists as i have over 6,000 songs at this time.

I run rs 2014
rsmods
cfsm
rs toolkit
rsasio

**Comment by BuongiornoTexas** [comment]
Hi @kevinl7778 - just saw this - I'm assuming this relates to your rs-manager problem. If not, can you please provide more detail on your the steps that result in this error (I need a bit more to work with).

**Comment by kevinl7778** [comment]
Hello yes it does, but I am having issues with both it would seam.

I have kust installed a fresh python 3.7.3, updated pip to get rsrtools installed in the virtual env and ron profilemanager --clone-profile and i still get warning root rocksmith save file has no player name, I have not run songlists but it was working after changing from python 3.11 to 3.7.3 and I still have the window open to try songlists.
![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/051175b5-128d-4657-afa4-1c9a45d1b270)

**Comment by kevinl7778** [comment]
I have not worked with python in a few years and I only am learning json now with arduino website stuff so I am wiz at programming but also not a complete noob.

Songlists runs as it did efore but gets tripped up on bad jason arrangmentname in file:
![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/7bfe1d06-ad49-41c7-8b07-bc63e978be87)

**Comment by kevinl7778** [comment]
And thank you for the help, I am really looking forward to getting the two items working.

**Comment by BuongiornoTexas** [comment]
OK - the first one looks like a steam save file problem. Those errors collectively are saying that rsrtools has found several profiledbs that it can't link to user names, and isn't able to link up your username to a profile db. So the first question is: is rocksmith actually working at all? Those errors suggest that there are problems with being able to load any user profile. Unfortunately, the screen grab also cuts off the first part of what was happening, which may give more clues - you might be able to scroll up to see what is happening.

rsrtools has been built around a maximum caution principle - if it sees stuff that is inconsistent or not working as expected, it will crash, hopefully without making any changes. So the first step is probably to sort out what is happening with your steam setup and go from there.

The second error sounds like you have a CDLC with a inconsistent arrangement data - can you check/validate this file in CFSM?

**Comment by kevinl7778** [comment]
I do use rs_mods and keep the last 5 copies of the profile as a backup but I dont think there kept in the steam forders, I will have a look at the profile files again. Or can it be that I have three users in rocksmith, I can delete two of them so its only my actual profile if thats the case.

As for the songs I used CFMS to look at the cdlc to find any matching text in the arrangment analyzer and in the folder but some of the songs hade no matching words so unless I run a program like your scanner to read each arrangment name and report back the filename the only way I was able to find them was to look at the last sucessfull folder to be scanned and poke around in the next alphabetical order folder for a song that might be is. ACDC back in black errored out as "BackOutBlackPlum_Bass but expected bass 2" any file I found was moved into a holding folder for now but I only got half way through "A" in half hour.

**Comment by kevinl7778** [comment]
Profile manager is working after removing some files last updated in 2020, not sure why there in here but I am going through the menus in the CMD now. Thanks

**Comment by BuongiornoTexas** [comment]
> Profile manager is working after removing some files last updated in 2020

OK - good luck with it. Make backups before doing anything I strongly suggest working with a cloned profile until you are sure you have everything sorted out (I'm guessing you don't want to lose progress so far).

**Comment by BuongiornoTexas** [comment]
And on the scanner failure - the arrangement SilentHill_Lead is classified as Lead in one place and Lead2 in another - this is worth a check in CFSM.

**Comment by kevinl7778** [comment]
I am running a repair proccess in cfms on 385 songs, on of them is silenthill so I will try again Teusday evening as Im in NJ and its about bed time. Thanks for the guidance.

CMD songlists:
![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/8cb502b3-858b-4045-8851-84051bff45d9)


CFMS:
![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/149d425f-b486-4361-88ac-cfdc414b7996)

**Comment by kevinl7778** [comment]
Hello again,

I went in after the repair with no gain so I looked at the arangements under edit song info and changed the second lead to combo and the son will pass now.

Is there a way to modify the scanner to move any failed song into a folder as a lot of songs are tripping the scanned.

after a fail I need to go into the "Working folder and delete config.toml and RS_Arangments.sql before I can mrun songlists again.


![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/fe09071c-e15c-4f35-9bf3-3bc7976c7fee)

**Comment by kevinl7778** [comment]
I pulled the DLC folder out of the rocksmith older and songlists runs and can see that some songs have more than one lead, bass combo ect. I am confused as to why it does not do the same for the files in the dlc folder that are named lead with alt and bunus attributes. I am going to see if rs_manager runs with only the stock song as well.

![image](https://github.com/BuongiornoTexas/rsrtools/assets/53792945/836b1dea-d65f-494e-88fa-ff4f0be6517c)

**Comment by BuongiornoTexas** [comment]
> I pulled the DLC folder out of the rocksmith older and songlists runs and can see that some songs have more than one lead, bass combo ect.

Rocksmith has things like lead, alt lead, and so on. These are the Lead, Lead1, and Lead2 names. Try relabelling your Combo arrangement to Lead2 and see if it still works.

> Is there a way to modify the scanner to move any failed song into a folder as a lot of songs are tripping the scanned.

This is a yes, but. Yes, you or someone else could grab the code and modify it to do this. 

The but is I don't have lot of spare time, and unfortunately this is not a feature I'm prepared to spend that time implementing (it's not really what rsrtools was designed for - you may do better asking the CFSM team, as part of their goal is to provide tools to fix song files.).

| after a fail I need to go into the "Working folder and delete config.toml and RS_Arangments.sql before I can mrun songlists again.

Is this because the database is corrupted, or is there a different problem? Also, what is the problem with config file? I can't remember if you can skip the scan on startup, but if you can, you could set up the config you want, exit to save the toml and then restart with a standard setup.

**Comment by BuongiornoTexas** [comment]
OK - I've gone back and tried to get things running at my end and found issues relating to python versions and package versions. Right now, I can't tell if the base package will work at all with **any** version of python due to these issues. 

I'd suggest you put a hold on any more testing until I have time to fully upgrade the package. I'm busy enough around home that this probably won't be for several weeks or possible months.

**Comment by kevinl7778** [comment]
I am running python 3.7.3 or the verision you state you were running as 3.11 would not work at all.

Your program seems to be workign fine other then tripping up on cdls with a lead2, rythym2 ect.

I will take a break from this for a while as I have electronics to make for a few people and two comerciarls to make but will return when the snow keeps me inside for the winter.

THanks again for looking into the errors with me.

**Comment by BuongiornoTexas** [comment]
> will return when the snow keeps me inside for the winter.

Well, at least that gives me a bit of time. :-)

**Comment by BuongiornoTexas** [comment]
@kevinl7778 New release is up. If the issue is still live, please try installing this and testing. After that, we can see if we can get it working with rs-manager as well.

**Comment by kevinl7778** [comment]
10-4

I have a few led projects for spring motorcycles going on but i Will be
checking this out this week through next weekend.

Feed back to follow for sure.

Thanks again,
KEvin

**Comment by kevinl7778** [comment]
In rs manager i get this error and a full list of song names is present in
the appdata/temp json file. Rsmanager also works to export csv and json to
the desktop. Python 3.12 and rsmanager is pointing to the pip install
location for importrsm.exe.

Export failed: an error has occurred.
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn
\"C:\\Users\\Kevin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\Scripts\\\"","path":"\"C:\\Users\\Kevin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\Scripts\\\"","spawnargs":["--silent","-a","76561198081152156","-p","Kevin","-sl","1","\"C:\\Users\\Kevin\\AppData\\Local\\Temp\\tmp-13096QmRWGeriyR4x\\songkeys.json\"","\"C:\\Users\\Kevin\\AppData\\Local\\Temp\\tmp-13096QmRWGeriyR4x\""]}

**Comment by BuongiornoTexas** [comment]
@kevinl7778 - it looks as though you are using the Microsoft store version of python. I probably won't be of any assistance if there are problems in that part of it. But let's assume all is working correctly there and knock out other possible issues first.

1) I'm assuming you installed rsrtools with pip into the main installation and not an environment. You check this by looking for importrsm.exe in the script directory. 
2) Start a command prompt and check that importrsm is working with `importrsm --help`.  
3) I think rs-manager needs an explicit path to importrsm - you probably need `importrsm.exe` at the end of your path in rs-manager. 

Let me know how these go.

**Comment by kevinl7778** [comment]
I was able to gwt the help menu last night with the longer code, somwthing
like python3 -m importers-h.

I tried both versions of python download, I believe with similar errors
however the pip package was not in the path at first so I can try again
tonight with a non ms store python download and the path set correctly for
both win environment and rsmanager.

I will let you know and send a few screen shots.

Kevin.

**Comment by BuongiornoTexas** [comment]
Kevin - you will need to find the file `importrsm.exe` in the scripts directory and test that directly in a command line with `importrsm --help`. (While it might be possibly to get a python -m command working with rs-manager, it's not really how rs-manager and importrsm are meant to interact).

**Comment by kevinl7778** [comment]
I found that the runpy error is due to have more than one python or extra
python's set in the path so i removed everything and used the windows store
install version and pip3/python3 and running importrsm -h fails but python3
-m rsrtools.importrsm -h works:


C:\Users\Kevin>importrsm -h
'importrsm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Kevin>python3 -m rsrtools.importrsm -h
usage: importrsm.py [-h] [-a <steam_id>] [-p <profile_name>] [--prfldb-path
<profile_path>] [--no-check] [--silent]
                    [-sl list_id song_file]
                    working_dir

Command line interface for loading song lists/set lists generated by
rs-manager into Rocksmith.

positional arguments:
  working_dir           Working directory for working files and arrangement
database (if any).

options:
  -h, --help            show this help message and exit
  -a <steam_id>, --account-id <steam_id>
                        Specify the steam account id for the Rocksmith
profile. This can be the the
account..............................................................................

Pip list:
C:\Users\Kevin>pip3 list -v
Package           Version Location

              Installer
----------------- -------
------------------------------------------------------------------------------------------------------------------------------------------
---------
rsrtools          1.1.0
C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages
pip



[image: image.png]
[image: image.png]

**Comment by BuongiornoTexas** [comment]
OK - your tests show have successfully installed rsrtools. Now you need to find the scripts folder and check if `importrsm.exe` is there (it should be). Then try to run that command either by a fully qualified path or by changing into that folder.

**Comment by BuongiornoTexas** [comment]
It will probably be in: `C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\scripts`

**Comment by kevinl7778** [comment]
I redid thing again and importrsm -h works after install things using pip3
for some reason,

[image: image.png]

**Comment by kevinl7778** [comment]
but it still fails in rs manager

**Comment by BuongiornoTexas** [comment]
Hi Kevin. Your image did not post correctly. Could you please retry, and could you also please take a screen shot of how you have setup importrsm in rs-manager?

**Comment by kevinl7778** [comment]
[image: image.png]Sorry I stepped away tp play the new guitar I got for my
44th b day. ITs about bedtime here in NJ but I can do a bit more in the
evening if you have some item you would like me to test.

[image: image.png]

**Comment by kevinl7778** [comment]
this is the path in rs-manager
C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Scripts\importrsm.exe

Rs-tools pipp3 location:
rsrtools          1.1.0
C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Lib\site-packages pip

Importrsm.exe location:
C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Scripts

**Comment by BuongiornoTexas** [comment]
Hi Kevin - no problems on the time delay. I'm in Australia, so it's always going to be patchy. 

I looks as though github is dropping images including in emails. You'll probably need to paste directly into a webclient on your pc (try snipping tool). 

But from what you've shown there, we can try the following:

- Open a command window and trying running this command: 

  `C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Scripts\importrsm.exe --help`

- Assuming help comes up as expected, try both of these in rs-manager (one or the other should work).

  `C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Scripts\importrsm.exe` or
  `C:\Users\Kevin\AppData\Local\Programs\Python\Python312\Scripts`

If these don't work, there may be a deeper problem with your rocksmith savefile - cross that bridge if we come to it.

Enjoy the noodling.

**Comment by BuongiornoTexas** [comment]
I'm assuming this is stale, and can close without further action.
